nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./node
    links:
        - mongodb
    ports:
        - "8080"
node2:
    build: ./node
    links:
        - mongodb
    ports:
        - "8080"
node3:
    build: ./node
    links:
        - mongodb
    ports:
        - "8080"
mongodb:
    image: mongodb
    ports:
        - "6379"


#to start the app we run: docker-compose up
#that will start all 5 of the containers and the thing will be up and runnig on port 80
#we can scale the project by runnning: docker-compose scale node=5