FROM nginx

COPY nginx.conf /etc/nginx/nginx.conf



#we build that with: docker build -t gogo/ngnix
#we create a ngnix container from the image and we link it to the node container: docker run -d --name nginx -p 80:80 --link 8080:8080 gogo/nginx

